# Generated by Django 5.1.7 on 2026-04-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypes',
            fields=[
                ('document_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'DocumentTypes',
            },
        ),
        migrations.CreateModel(
            name='ProductionObjects',
            fields=[
                ('object_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ProductionObjects',
            },
        ),
    ]
