# Generated by Django 5.1.7 on 2026-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_cfg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttypes',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='doc_templates/'),
        ),
        migrations.AddField(
            model_name='documenttypes',
            name='template_html',
            field=models.TextField(blank=True),
        ),
    ]
