# Generated by Django 5.1.7 on 2026-05-02 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0003_reference_columns_and_selections'),
        ('templates_cfg', '0002_documenttypes_template_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionobjects',
            name='source_record',
            field=models.ForeignKey(blank=True, help_text='Если задано — объект создан из записи справочника.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_objects', to='bpm.dictionaryrecord'),
        ),
    ]
