# Generated by Django 5.1.7 on 2026-05-02 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_documents_generated_file'),
        ('processes', '0001_initial'),
        ('requisites', '0003_requisites_placeholder_key'),
        ('templates_cfg', '0002_documenttypes_template_file_and_more'),
        ('users', '0003_users_password_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDictionary',
            fields=[
                ('dictionary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'reference dictionaries',
                'db_table': 'ReferenceDictionaries',
            },
        ),
        migrations.CreateModel(
            name='BusinessProcessTemplate',
            fields=[
                ('bpt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('legacy_process', models.ForeignKey(help_text='Процесс из базовой модели: нужен для совместимости с Documents.process_id', on_delete=django.db.models.deletion.PROTECT, related_name='business_templates', to='processes.processes')),
            ],
            options={
                'db_table': 'BusinessProcessTemplates',
            },
        ),
        migrations.CreateModel(
            name='BusinessProcessInstance',
            fields=[
                ('bpi_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('in_progress', 'in_progress'), ('completed', 'completed')], default='in_progress', max_length=20)),
                ('current_step_order', models.PositiveIntegerField(default=1)),
                ('context_json', models.TextField(default='{}')),
                ('dictionary_lookup_key', models.CharField(blank=True, help_text='Ключ поиска в справочнике (например название подразделения)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legacy_process', models.ForeignKey(help_text='Дублирует шаблон: для поля Documents.process_id', on_delete=django.db.models.deletion.PROTECT, related_name='bpm_instances', to='processes.processes')),
                ('production_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bpm_instances', to='templates_cfg.productionobjects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bpm_instances', to='users.users')),
                ('business_process_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='bpm.businessprocesstemplate')),
            ],
            options={
                'db_table': 'BusinessProcessInstances',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProcessDocumentTemplate',
            fields=[
                ('pdt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('step_order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('business_process_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='bpm.businessprocesstemplate')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_document_templates', to='templates_cfg.documenttypes')),
            ],
            options={
                'db_table': 'ProcessDocumentTemplates',
                'ordering': ('business_process_template', 'step_order'),
                'unique_together': {('business_process_template', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='ProcessDocumentInstance',
            fields=[
                ('pdi_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bpm.businessprocessinstance')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bpm_document_slot', to='documents.documents')),
                ('process_document_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='bpm.processdocumenttemplate')),
            ],
            options={
                'db_table': 'ProcessDocumentInstances',
                'unique_together': {('business_process_instance', 'process_document_template')},
            },
        ),
        migrations.CreateModel(
            name='FieldSourceRule',
            fields=[
                ('rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('manual', 'manual'), ('dictionary', 'dictionary'), ('process_object', 'process_object'), ('previous_document', 'previous_document'), ('process_context', 'process_context')], default='manual', max_length=32)),
                ('dictionary_field', models.CharField(blank=True, help_text='Ключ в JSON записи справочника, напр. signer_name', max_length=255)),
                ('object_field', models.CharField(blank=True, help_text='name | object_type — поле производственного объекта', max_length=64)),
                ('context_key', models.CharField(blank=True, help_text='Ключ в context_json экземпляра БП (process_context)', max_length=255)),
                ('requisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpm_field_rules', to='requisites.requisites')),
                ('source_requisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_as_source_requisite', to='requisites.requisites')),
                ('process_document_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_rules', to='bpm.processdocumenttemplate')),
                ('source_process_document_template', models.ForeignKey(blank=True, help_text='Предыдущий шаг, из документа которого копируем', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_as_previous_step', to='bpm.processdocumenttemplate')),
                ('dictionary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_rules', to='bpm.referencedictionary')),
            ],
            options={
                'db_table': 'FieldSourceRules',
                'unique_together': {('process_document_template', 'requisite')},
            },
        ),
        migrations.CreateModel(
            name='DictionaryRecord',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lookup_key', models.CharField(db_index=True, max_length=255)),
                ('payload_json', models.TextField(default='{}')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='bpm.referencedictionary')),
            ],
            options={
                'db_table': 'DictionaryRecords',
                'unique_together': {('dictionary', 'lookup_key')},
            },
        ),
    ]
