# Generated by Django 5.1.7 on 2026-05-02 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0001_initial_bpm_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocessinstance',
            name='dictionary_record',
            field=models.ForeignKey(blank=True, help_text='Выбранная запись справочника при запуске БП', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bpm_instances', to='bpm.dictionaryrecord'),
        ),
    ]
