# Generated by Django 5.1.7 on 2026-05-02 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0002_operationlog_text_and_instance_dictionary_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocesstemplate',
            name='objects_dictionary',
            field=models.ForeignKey(blank=True, help_text='Справочник объектов: запись при запуске БП становится производственным объектом документов.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bpm_templates_as_objects', to='bpm.referencedictionary'),
        ),
        migrations.AlterField(
            model_name='fieldsourcerule',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Ручной ввод'), ('dictionary', 'Справочник'), ('process_object', 'Объект БП'), ('previous_document', 'Предыдущий документ'), ('process_context', 'Контекст процесса')], default='manual', max_length=32),
        ),
        migrations.CreateModel(
            name='DictionaryColumn',
            fields=[
                ('column_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='bpm.referencedictionary')),
            ],
            options={
                'db_table': 'DictionaryColumns',
                'ordering': ('dictionary', 'sort_order', 'key'),
                'unique_together': {('dictionary', 'key')},
            },
        ),
        migrations.CreateModel(
            name='InstanceDictionarySelection',
            fields=[
                ('selection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_selections', to='bpm.businessprocessinstance')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_selections', to='bpm.referencedictionary')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_selections', to='bpm.dictionaryrecord')),
            ],
            options={
                'db_table': 'InstanceDictionarySelections',
                'unique_together': {('business_process_instance', 'dictionary')},
            },
        ),
    ]
