# Generated by Django 5.1.7 on 2026-05-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0003_reference_columns_and_selections'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedictionary',
            name='selection_column_key',
            field=models.CharField(blank=True, help_text='Колонка, по значению которой оператор выбирает запись; также формируется внутренний код строки.', max_length=64),
        ),
    ]
