# Generated by Django 5.1.7 on 2026-04-29 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processes', '0001_initial'),
        ('templates_cfg', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='templates_cfg.documenttypes')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='templates_cfg.productionobjects')),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='processes.processes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='users.users')),
            ],
            options={
                'db_table': 'Documents',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentLinks',
            fields=[
                ('doc_link_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('step_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_links', to='processes.processsteps')),
                ('source_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='documents.documents')),
                ('target_document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='documents.documents')),
            ],
            options={
                'db_table': 'DocumentLinks',
            },
        ),
    ]
