# Generated by Django 5.1.7 on 2026-04-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('filled', 'filled'), ('generated', 'generated'), ('archived', 'archived')], default='draft', max_length=50),
        ),
    ]
