# Generated by Django 5.1.7 on 2026-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documents_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='generated_html',
            field=models.TextField(blank=True),
        ),
    ]
