# Generated by Django 5.1.7 on 2026-04-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documents_generated_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='generated_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_docs/'),
        ),
    ]
