# Generated by Django 5.1.7 on 2026-04-29 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='roles.roles')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
