# Generated by Django 5.1.7 on 2026-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
