# Generated by Django 5.1.7 on 2026-04-29 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('templates_cfg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('requisite_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=30)),
                ('is_required', models.BooleanField(default=False)),
                ('document_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='templates_cfg.documenttypes')),
            ],
            options={
                'db_table': 'Requisites',
            },
        ),
        migrations.CreateModel(
            name='RequisiteLinks',
            fields=[
                ('req_link_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inheritance_rule', models.CharField(default='copy_if_empty', max_length=100)),
                ('source_requisite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='requisites.requisites')),
                ('target_requisite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_links', to='requisites.requisites')),
            ],
            options={
                'db_table': 'RequisiteLinks',
            },
        ),
        migrations.CreateModel(
            name='RequisiteValues',
            fields=[
                ('value_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisite_values', to='documents.documents')),
                ('requisite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='requisites.requisites')),
            ],
            options={
                'db_table': 'RequisiteValues',
                'unique_together': {('document_id', 'requisite_id')},
            },
        ),
    ]
