# Generated by Django 5.1.7 on 2026-04-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='field_kind',
            field=models.CharField(choices=[('constant', 'constant'), ('variable', 'variable')], default='variable', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='data_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date'), ('select', 'select'), ('boolean', 'boolean')], default='text', max_length=30),
        ),
    ]
