# Generated by Django 5.1.7 on 2026-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisites', '0002_requisites_field_kind_alter_requisites_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='placeholder_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
