# Generated by Django 5.1.7 on 2026-04-29 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processes',
            fields=[
                ('process_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Processes',
            },
        ),
        migrations.CreateModel(
            name='ProcessSteps',
            fields=[
                ('step_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('step_order', models.PositiveIntegerField()),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='processes.processes')),
            ],
            options={
                'db_table': 'ProcessSteps',
                'ordering': ('process_id', 'step_order'),
                'unique_together': {('process_id', 'step_order')},
            },
        ),
    ]
