# Generated by Django 5.1.7 on 2026-04-29 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('processes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('operation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation_datetime', models.DateTimeField(auto_now_add=True)),
                ('operation_result', models.CharField(max_length=255)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='documents.documents')),
                ('step_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_logs', to='processes.processsteps')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_logs', to='users.users')),
            ],
            options={
                'db_table': 'OperationLog',
                'ordering': ('-operation_datetime',),
            },
        ),
    ]
