# Generated by Django 5.1.7 on 2026-04-29 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documents_status'),
        ('logs', '0001_initial'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='document_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='documents.documents'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='step_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_logs', to='processes.processsteps'),
        ),
    ]
