# Generated by Django 5.1.7 on 2026-05-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_operationlog_document_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='operation_result',
            field=models.TextField(),
        ),
    ]
